"use client";

import { useState, useEffect } from "react";

interface TaskType {
  id: number;
  name: string;
  label: string;
}

interface Agent {
  id: number;
  name: string;
  role: string;
  openTaskCount: number;
}

interface CreateTaskModalProps {
  onClose: () => void;
  onCreated: () => void;
}

const PRIORITY_OPTIONS = [
  { value: "URGENT", label: "Urgent", color: "text-red-400" },
  { value: "HIGH", label: "High", color: "text-orange-400" },
  { value: "MEDIUM", label: "Medium", color: "text-amber-400" },
  { value: "LOW", label: "Low", color: "text-zinc-400" },
];

const SLA_PRESETS = [
  { label: "30 min", value: 30 },
  { label: "1 hr", value: 60 },
  { label: "2 hr", value: 120 },
  { label: "4 hr", value: 240 },
];

export default function CreateTaskModal({ onClose, onCreated }: CreateTaskModalProps) {
  const [taskTypes, setTaskTypes] = useState<TaskType[]>([]);
  const [agents, setAgents] = useState<Agent[]>([]);
  const [loadingData, setLoadingData] = useState(true);

  const [title, setTitle] = useState("");
  const [taskTypeId, setTaskTypeId] = useState<number | "">("");
  const [priority, setPriority] = useState("HIGH");
  const [entityId, setEntityId] = useState("");
  const [storeId, setStoreId] = useState("");
  const [slaMinutes, setSlaMinutes] = useState(60);
  const [customSla, setCustomSla] = useState("");
  const [assignedToId, setAssignedToId] = useState<number | "">("");
  const [note, setNote] = useState("");

  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function loadData() {
      const [typesRes, teamRes] = await Promise.all([
        fetch("/api/task-types"),
        fetch("/api/roster"),
      ]);
      const typesData = typesRes.ok ? await typesRes.json() : { types: [] };
      const teamData = teamRes.ok ? await teamRes.json() : { members: [] };

      setTaskTypes(typesData.types ?? []);
      // Only show ACTIVE or ON_FIELD agents
      const activeMembers = (teamData.members ?? []).filter(
        (m: { rosterEntry?: { status: string } | null; role: string }) =>
          m.rosterEntry?.status === "ACTIVE" || m.rosterEntry?.status === "ON_FIELD"
      );
      setAgents(
        activeMembers.map((m: { userId: number; name: string; role: string; openTaskCount: number }) => ({
          id: m.userId,
          name: m.name,
          role: m.role,
          openTaskCount: m.openTaskCount,
        }))
      );
      setLoadingData(false);
    }
    loadData();
  }, []);

  const effectiveSla = customSla ? parseInt(customSla, 10) : slaMinutes;

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!title.trim() || !taskTypeId || !entityId || !effectiveSla) {
      setError("Please fill in all required fields");
      return;
    }
    if (isNaN(Number(entityId)) || Number(entityId) <= 0) {
      setError("Order ID must be a positive number");
      return;
    }

    setError(null);
    setSubmitting(true);

    try {
      const res = await fetch("/api/tasks", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: title.trim(),
          taskTypeId: Number(taskTypeId),
          priority,
          entityId: Number(entityId),
          storeId: storeId ? Number(storeId) : null,
          slaMinutes: effectiveSla,
          assignedToId: assignedToId ? Number(assignedToId) : null,
          note: note.trim() || null,
        }),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error ?? "Failed to create task");
      }

      onCreated();
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to create task");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="w-full max-w-lg bg-zinc-900 border border-zinc-700 rounded-2xl shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="px-6 py-4 border-b border-zinc-800 flex items-center justify-between">
          <div>
            <h2 className="text-base font-semibold text-white">Create Manual Task</h2>
            <p className="text-xs text-zinc-500 mt-0.5">Add an ad-hoc task not auto-generated by the engine</p>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-lg text-zinc-500 hover:text-zinc-300 hover:bg-zinc-800 transition-colors"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Form */}
        {loadingData ? (
          <div className="flex items-center justify-center py-16">
            <div className="w-5 h-5 border-2 border-zinc-700 border-t-blue-500 rounded-full animate-spin" />
          </div>
        ) : (
          <form onSubmit={handleSubmit} className="px-6 py-5 space-y-4 max-h-[70vh] overflow-y-auto">
            {/* Title */}
            <div>
              <label className="block text-xs font-medium text-zinc-400 mb-1.5">
                Task Title <span className="text-red-400">*</span>
              </label>
              <input
                type="text"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="e.g. Call patient to reschedule appointment"
                className="w-full px-3 py-2 bg-zinc-800 border border-zinc-700 rounded-lg text-sm text-zinc-200 placeholder-zinc-600 focus:outline-none focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
              />
            </div>

            {/* Task Type + Priority */}
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-xs font-medium text-zinc-400 mb-1.5">
                  Task Type <span className="text-red-400">*</span>
                </label>
                <select
                  value={taskTypeId}
                  onChange={(e) => setTaskTypeId(e.target.value ? Number(e.target.value) : "")}
                  className="w-full px-3 py-2 bg-zinc-800 border border-zinc-700 rounded-lg text-sm text-zinc-200 focus:outline-none focus:ring-1 focus:ring-blue-500"
                >
                  <option value="">Select type…</option>
                  {taskTypes.map((t) => (
                    <option key={t.id} value={t.id}>{t.label}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-xs font-medium text-zinc-400 mb-1.5">Priority</label>
                <select
                  value={priority}
                  onChange={(e) => setPriority(e.target.value)}
                  className="w-full px-3 py-2 bg-zinc-800 border border-zinc-700 rounded-lg text-sm text-zinc-200 focus:outline-none focus:ring-1 focus:ring-blue-500"
                >
                  {PRIORITY_OPTIONS.map((p) => (
                    <option key={p.value} value={p.value}>{p.label}</option>
                  ))}
                </select>
              </div>
            </div>

            {/* Order ID + Store ID */}
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-xs font-medium text-zinc-400 mb-1.5">
                  Order ID <span className="text-red-400">*</span>
                </label>
                <input
                  type="number"
                  value={entityId}
                  onChange={(e) => setEntityId(e.target.value)}
                  placeholder="e.g. 12345"
                  className="w-full px-3 py-2 bg-zinc-800 border border-zinc-700 rounded-lg text-sm text-zinc-200 placeholder-zinc-600 focus:outline-none focus:ring-1 focus:ring-blue-500"
                />
              </div>
              <div>
                <label className="block text-xs font-medium text-zinc-400 mb-1.5">Store ID</label>
                <input
                  type="number"
                  value={storeId}
                  onChange={(e) => setStoreId(e.target.value)}
                  placeholder="Optional"
                  className="w-full px-3 py-2 bg-zinc-800 border border-zinc-700 rounded-lg text-sm text-zinc-200 placeholder-zinc-600 focus:outline-none focus:ring-1 focus:ring-blue-500"
                />
              </div>
            </div>

            {/* SLA */}
            <div>
              <label className="block text-xs font-medium text-zinc-400 mb-1.5">
                SLA Deadline <span className="text-red-400">*</span>
              </label>
              <div className="flex gap-2 flex-wrap">
                {SLA_PRESETS.map((p) => (
                  <button
                    key={p.value}
                    type="button"
                    onClick={() => { setSlaMinutes(p.value); setCustomSla(""); }}
                    className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors ${
                      slaMinutes === p.value && !customSla
                        ? "bg-blue-600/15 border-blue-500/40 text-blue-400"
                        : "bg-zinc-800 border-zinc-700 text-zinc-400 hover:border-zinc-600"
                    }`}
                  >
                    {p.label}
                  </button>
                ))}
                <input
                  type="number"
                  value={customSla}
                  onChange={(e) => setCustomSla(e.target.value)}
                  placeholder="Custom (min)"
                  className="px-3 py-1.5 bg-zinc-800 border border-zinc-700 rounded-lg text-xs text-zinc-200 placeholder-zinc-600 focus:outline-none focus:ring-1 focus:ring-blue-500 w-28"
                />
              </div>
            </div>

            {/* Assign to */}
            <div>
              <label className="block text-xs font-medium text-zinc-400 mb-1.5">
                Assign To
                <span className="ml-1 text-zinc-600 font-normal">(active agents only)</span>
              </label>
              <select
                value={assignedToId}
                onChange={(e) => setAssignedToId(e.target.value ? Number(e.target.value) : "")}
                className="w-full px-3 py-2 bg-zinc-800 border border-zinc-700 rounded-lg text-sm text-zinc-200 focus:outline-none focus:ring-1 focus:ring-blue-500"
              >
                <option value="">Unassigned</option>
                {agents.map((a) => (
                  <option key={a.id} value={a.id}>
                    {a.name} ({a.openTaskCount} open tasks)
                  </option>
                ))}
              </select>
              {agents.length === 0 && (
                <p className="mt-1 text-[10px] text-amber-400">
                  No active agents on roster today. Task will remain unassigned.
                </p>
              )}
            </div>

            {/* Note */}
            <div>
              <label className="block text-xs font-medium text-zinc-400 mb-1.5">Note</label>
              <textarea
                value={note}
                onChange={(e) => setNote(e.target.value)}
                rows={2}
                placeholder="Optional context or instructions…"
                className="w-full px-3 py-2 bg-zinc-800 border border-zinc-700 rounded-lg text-sm text-zinc-200 placeholder-zinc-600 focus:outline-none focus:ring-1 focus:ring-blue-500 resize-none"
              />
            </div>

            {/* Error */}
            {error && (
              <div className="px-4 py-2.5 bg-red-500/10 border border-red-500/20 rounded-lg text-xs text-red-400">
                {error}
              </div>
            )}
          </form>
        )}

        {/* Footer */}
        <div className="px-6 py-4 border-t border-zinc-800 flex items-center justify-end gap-3">
          <button
            type="button"
            onClick={onClose}
            disabled={submitting}
            className="px-4 py-2 text-sm text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800 rounded-lg transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={handleSubmit as unknown as React.MouseEventHandler}
            disabled={submitting || loadingData}
            className="px-5 py-2 bg-blue-600 hover:bg-blue-500 disabled:bg-blue-600/40 text-white text-sm font-medium rounded-lg transition-colors flex items-center gap-2"
          >
            {submitting && (
              <div className="w-3.5 h-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
            )}
            {submitting ? "Creating…" : "Create Task"}
          </button>
        </div>
      </div>
    </div>
  );
}
